/*
 http://www.gnu.org/licenses/gpl-3.0.html GNU General Public License v3

*/
var editorActive=1;function applyTags(a,b,c){$j("input#tags").jTagging($j("div#form_tags_list")," ",a,b,c);$j("input#page_blocks").jTagging($j("div#form_block_list")," ",a,b,c)}
function confirmer(a,b){$j("#confirm").modal({opacity:80,closeHTML:"<a href='#' title='Close' class='modal-close'>x</a>",position:["30%"],overlayId:"confirm-overlay",containerId:"confirm-container",onOpen:function(c){c.overlay.fadeIn("fast",function(){c.container.fadeIn("fast",function(){c.data.fadeIn("fast")})})},onShow:function(c){$j(".message",c.data[0]).append(a);$j(".yes",c.data[0]).click(function(){$j.isFunction(b)&&b.apply();$j.modal.close()})}})}
function actConfirm(){$j("a.confirm-del").each(function(){$j(this).click(function(a){var b=$j(this).attr("href");a.preventDefault();confirmer("Are you sure?",function(){if(actionType==="admin")window.location.href=b;else actionType==="theme"&&$j.post(b,function(){if($j("a#permalinkClick").length>=1)pLck=$j("a#permalinkClick").attr("name");else{pLck=location.href.replace("#comments","");pLck=pLck.replace("#commentform","")}setTimeout(function(){$j("#ajaxContent2").load(pLck+" #ajaxContent1")},1600)})})})});
actionType==="admin"&&$j("form.input-confirm").submit(function(a){a.preventDefault();var b=$j(this).attr("action");confirmer("Are you sure?",function(){window.location.href=b})})}
function useCkeditor(a){if(!editor){editorActive=2;CKEDITOR.plugins.addExternal("pfxGeSHi",pfxSiteUrl+"admin/jscript/editor-plugins/pfxGeSHi/");CKEDITOR.plugins.addExternal("pfxPageBreak",pfxSiteUrl+"admin/jscript/editor-plugins/pfxPageBreak/");CKEDITOR.plugins.addExternal("pfxImage",pfxSiteUrl+"admin/jscript/editor-plugins/pfxImage/");CKEDITOR.plugins.addExternal("pfxFind",pfxSiteUrl+"admin/jscript/editor-plugins/pfxFind/");CKEDITOR.plugins.addExternal("pfxLink",pfxSiteUrl+"admin/jscript/editor-plugins/pfxLink/");
CKEDITOR.plugins.addExternal("codemirror",pfxSiteUrl+"admin/jscript/editor-plugins/codemirror/");CKEDITOR.config.customConfig=pfxSiteUrl+"admin/jscript/ckeditor-config.js";if(a==="wysiwyg"){editorMode=1;editor=CKEDITOR.replaceAll("ck-textarea")}else if(a==="source"){editorMode=2;editor=CKEDITOR.replaceAll("ck-textarea-php")}}}function CloseEditor(a){a=CKEDITOR.instances[a];a.execCommand("mirrorSnapshot");a.destroy();editor=null;$j(function(){$j("div.editor-controls").hide()})}
function SwitchToolBar(a){var b=CKEDITOR.instances[a];b.execCommand("mirrorSnapshot");editorMode=CKEDITOR.instances[a].mode=="wysiwyg"?1:2;b.destroy();editor=null;pfxToolBar=pfxToolBar=="Small"?"Large":"Small";editor=CKEDITOR.replace(a)}function MirrorUpdate(){for(i in CKEDITOR.instances)CKEDITOR.instances[i].execCommand("mirrorSnapshot")}function switchUploader(){$j("form#upload_form").slideDown("slow","easeInOutQuad");$j("input#upload-control").remove()}
function showNicEdit(){nicOptions={iconsPath:pfxSiteUrl+"admin/admin/theme/images/png/nicEditorIcons.png",buttonList:["bold","italic","underline","strikeThrough","ol","ul","image","link","bgcolor","forecolor","xhtml"]};actionType=="admin"?bkLib.onDomLoaded(function(){nicEditors.allTextAreas(nicOptions)}):nicEditors.allTextAreas(nicOptions);edtChk=1}
function showCodeM(){$j(".form_item_textarea-codemirror").each(function(){var a=$j(this).attr("id"),b=pfxSiteUrl+"admin/jscript/editor-plugins/codemirror/";CodeMirror.fromTextArea(a,{stylesheet:b+"css/colors.css",path:b+"js/",parserfile:"parsemixed.js",passDelay:300,passTime:35,continuousScanning:1E3,undoDepth:1,height:"18em",textWrapping:true,lineNumbers:false,enterMode:"flat"})}).removeClass("form_item_textarea-codemirror");edtChk=1}
function editorCheck(){$j(".ck-textarea").length>=1&&useCkeditor("wysiwyg");$j(".ck-textarea-php").length>=1&&useCkeditor("source");$j(".form_item_textarea_no_ckeditor").length>=1&&showNicEdit();$j(".form_item_textarea-codemirror").length>=1&&showCodeM()}$j(function(){actConfirm();actionType==="admin"&&editorCheck()});
$j(document).ready(function(){$j("body").append('<div id="confirm"><div class="header"><span>Confirm</span></div><div class="message"></div><div class="buttons"><div class="no simplemodal-close">No</div><div class="yes">Yes</div></div></div>');if($j.support.htmlSerialize===true){var a=1,b=$j("input#tags").length+$j("input#page_blocks").length,c={backgroundColor:"#EF2929",color:"#ffffff",padding:"1px 4px 1px 4px"},d={padding:"1px 4px 1px 4px",backgroundColor:"#ffffff",color:"#EF2929"},e={backgroundColor:"#EF2929",
color:"#ffffff",padding:"1px 4px 1px 4px",textDecoration:"none"};if(b>=1)if(a===1){a=2;applyTags(d,c,e)}$j(document).ajaxStop(function(){if(a===1){b=$j("input#tags").length+$j("input#page_blocks").length;if(b>=1){a=2;applyTags(d,c,e)}}})}$j(document).ajaxStop(function(){actConfirm();editorActive===1&&actionType==="admin"&&editorCheck()})});