var select={};
(function(){function p(a,c){for(;a&&a.parentNode!=c;)a=a.parentNode;return a}function t(a,c){for(;!a.previousSibling&&a.parentNode!=c;)a=a.parentNode;return p(a.previousSibling,c)}select.ie_selection=document.selection&&document.selection.createRangeCollection;select.scrollToNode=function(a,c){if(a){for(var b=a,e=document.body,d=document.documentElement,f=!b.nextSibling||!b.nextSibling.nextSibling||!b.nextSibling.nextSibling.nextSibling,g=0;b&&!b.offsetTop;){g++;b=b.previousSibling}if(g==0)f=false;
if(!(webkit&&b&&b.offsetTop==5&&b.offsetLeft==5)){g=g*(b?b.offsetHeight:0);var j=0,h=a?a.offsetWidth:0;for(b=b;b&&b.offsetParent;){g+=b.offsetTop;isBR(b)||(j+=b.offsetLeft);b=b.offsetParent}b=e.scrollLeft||d.scrollLeft||0;e=e.scrollTop||d.scrollTop||0;var k=false,l=window.innerWidth||d.clientWidth||0;if(c||h<l){if(c){var n=select.offsetInNode(a),m=nodeText(a).length;if(m)j+=h*(n/m)}h=j-b;if(h<0||h>l){b=j;k=true}}j=g-e;if(j<0||f||j>(window.innerHeight||d.clientHeight||0)-50){e=f?1E6:g;k=true}k&&window.scrollTo(b,
e)}}};select.scrollToCursor=function(a){select.scrollToNode(select.selectionTopNode(a,true)||a.firstChild,true)};var i=null;select.snapshotChanged=function(){if(i)i.changed=true};select.snapshotReplaceNode=function(a,c,b,e){function d(f){if(a==f.node){i.changed=true;if(b&&f.offset>b)f.offset-=b;else{f.node=c;f.offset+=e||0}}}if(i){d(i.start);d(i.end)}};select.snapshotMove=function(a,c,b,e,d){function f(g){if(a==g.node&&(!d||g.offset==0)){i.changed=true;g.node=c;g.offset=e?Math.max(0,g.offset+b):b}}
if(i){f(i.start);f(i.end)}};if(select.ie_selection){var u=function(a){function c(h){for(var k=null;!k&&h;){k=h.nextSibling;h=h.parentNode}return b(k)}function b(h){for(;h&&h.firstChild;)h=h.firstChild;return{node:h,offset:0}}var e=document.selection.createRange();e.collapse(a);a=e.parentElement();if(!isAncestor(document.body,a))return null;if(!a.firstChild)return b(a);var d=e.duplicate();d.moveToElementText(a);d.collapse(true);for(var f=a.firstChild;f;f=f.nextSibling){if(f.nodeType==3){var g=f.nodeValue.length;
d.move("character",g)}else{d.moveToElementText(f);d.collapse(false)}var j=e.compareEndPoints("StartToStart",d);if(j==0)return c(f);if(j!=1){if(f.nodeType!=3)return b(f);d.setEndPoint("StartToEnd",e);return{node:f,offset:g-d.text.length}}}return c(a)};select.markSelection=function(){i=null;if(document.selection){var a=u(true),c=u(false);if(a&&c)i={start:a,end:c,changed:false}}};select.selectMarked=function(){function a(e){var d=document.body.createTextRange(),f=e.node;if(f)if(f.nodeType==3){d.moveToElementText(f.parentNode);
for(e=e.offset;f.previousSibling;){f=f.previousSibling;e+=(f.innerText||"").length}d.move("character",e)}else{d.moveToElementText(f);d.collapse(true)}else{d.moveToElementText(document.body);d.collapse(false)}return d}if(i&&i.changed){var c=a(i.start),b=a(i.end);c.setEndPoint("StartToEnd",b);c.select()}};select.offsetInNode=function(a){var c=document.selection;if(!c)return 0;c=c.createRange();var b=c.duplicate();try{b.moveToElementText(a)}catch(e){return 0}c.setEndPoint("StartToStart",b);return c.text.length};
select.selectionTopNode=function(a,c){function b(l,n){if(n.nodeType==3){for(var m=0,o=n.previousSibling;o&&o.nodeType==3;){m+=o.nodeValue.length;o=o.previousSibling}if(o){try{l.moveToElementText(o)}catch(x){return false}l.collapse(false)}else l.moveToElementText(n.parentNode);m&&l.move("character",m)}else try{l.moveToElementText(n)}catch(y){return false}return true}var e=document.selection;if(!e)return false;var d=e.createRange(),f=d.duplicate();d.collapse(c);var g=d.parentElement();if(g&&isAncestor(a,
g)){f.moveToElementText(g);if(d.compareEndPoints("StartToStart",f)==1)return p(g,a)}c=0;for(g=a.childNodes.length-1;c<g;){var j=Math.ceil((g+c)/2),h=a.childNodes[j];if(!h)return false;if(!b(f,h))return false;if(d.compareEndPoints("StartToStart",f)==1)c=j;else g=j-1}if(c==0){e=e.createRange();d=e.duplicate();try{d.moveToElementText(a)}catch(k){return null}if(e.compareEndPoints("StartToStart",d)==0)return null}return a.childNodes[c]||null};select.focusAfterNode=function(a,c){var b=document.body.createTextRange();
b.moveToElementText(a||c);b.collapse(!a);b.select()};select.somethingSelected=function(){var a=document.selection;return a&&a.createRange().text!=""};var v=function(a){var c=document.selection;if(c){c=c.createRange();c.pasteHTML(a);c.collapse(false);c.select()}};select.insertNewlineAtCursor=function(){v("<br>")};select.insertTabAtCursor=function(){v("\u00a0\u00a0\u00a0\u00a0")};select.cursorPos=function(a,c){var b=document.selection;if(!b)return null;for(var e=select.selectionTopNode(a,c);e&&!isBR(e);)e=
e.previousSibling;b=b.createRange();var d=b.duplicate();b.collapse(c);if(e){d.moveToElementText(e);d.collapse(false)}else{try{d.moveToElementText(a)}catch(f){return null}d.collapse(true)}b.setEndPoint("StartToStart",d);return{node:e,offset:b.text.length}};select.setCursorPos=function(a,c,b){function e(f){var g=document.body.createTextRange();if(f.node){g.moveToElementText(f.node);g.collapse(false)}else{g.moveToElementText(a);g.collapse(true)}g.move("character",f.offset);return g}var d=e(c);b&&b!=
c&&d.setEndPoint("EndToEnd",e(b));d.select()};select.getBookmark=function(a){var c=select.cursorPos(a,true);a=select.cursorPos(a,false);if(c&&a)return{from:c,to:a}};select.setBookmark=function(a,c){c&&select.setCursorPos(a,c.from,c.to)}}else{var s=function(a,c){for(;a.nodeType!=3&&!isBR(a);){var b=a.childNodes[c]||a.nextSibling;for(c=0;!b&&a.parentNode;){a=a.parentNode;b=a.nextSibling}a=b;if(!b)break}return{node:a,offset:c}};select.markSelection=function(){var a=window.getSelection();if(!a||a.rangeCount==
0)return i=null;a=a.getRangeAt(0);i={start:s(a.startContainer,a.startOffset),end:s(a.endContainer,a.endOffset),changed:false}};select.selectMarked=function(){function a(){if(b.start.node==b.end.node&&b.start.offset==b.end.offset){var d=window.getSelection();if(!d||d.rangeCount==0)return true;d=d.getRangeAt(0);d=s(d.startContainer,d.startOffset);return b.start.node!=d.node||b.start.offset!=d.offset}}function c(d,f){if(d.node)d.offset==0?e["set"+f+"Before"](d.node):e["set"+f](d.node,d.offset);else e.setStartAfter(document.body.lastChild||
document.body)}var b=i;if(b&&(b.changed||webkit&&a())){var e=document.createRange();c(b.end,"End");c(b.start,"Start");r(e)}};var r=function(a){var c=window.getSelection();if(c){c.removeAllRanges();c.addRange(a)}},q=function(){var a=window.getSelection();return!a||a.rangeCount==0?false:a.getRangeAt(0)};select.selectionTopNode=function(a,c){var b=q();if(!b)return false;var e=c?b.startContainer:b.endContainer,d=c?b.startOffset:b.endOffset;window.opera&&!c&&b.endContainer==a&&b.endOffset==b.startOffset+
1&&a.childNodes[b.startOffset]&&isBR(a.childNodes[b.startOffset])&&d--;return e.nodeType==3?d>0?p(e,a):t(e,a):e.nodeName.toUpperCase()=="HTML"?d==1?null:a.lastChild:e==a?d==0?null:e.childNodes[d-1]:d==e.childNodes.length?p(e,a):d==0?t(e,a):p(e.childNodes[d-1],a)};select.focusAfterNode=function(a,c){var b=document.createRange();b.setStartBefore(c.firstChild||c);if(a&&!a.firstChild)b.setEndAfter(a);else a?b.setEnd(a,a.childNodes.length):b.setEndBefore(c.firstChild||c);b.collapse(false);r(b)};select.somethingSelected=
function(){var a=q();return a&&!a.collapsed};select.offsetInNode=function(a){var c=q();if(!c)return 0;c=c.cloneRange();c.setStartBefore(a);return c.toString().length};var w=function(a){var c=q();if(c){c.deleteContents();c.insertNode(a);webkitLastLineHack(document.body);if(window.opera&&isBR(a)&&isSpan(a.parentNode)){c=a.nextSibling;var b=a.parentNode,e=b.parentNode;e.insertBefore(a,b.nextSibling);for(b="";c&&c.nodeType==3;c=c.nextSibling){b+=c.nodeValue;removeElement(c)}e.insertBefore(makePartSpan(b,
document),a.nextSibling)}c=document.createRange();c.selectNode(a);c.collapse(false);r(c)}};select.insertNewlineAtCursor=function(){w(document.createElement("BR"))};select.insertTabAtCursor=function(){w(document.createTextNode("\u00a0\u00a0\u00a0\u00a0"))};select.cursorPos=function(a,c){var b=q();if(b){for(var e=select.selectionTopNode(a,c);e&&!isBR(e);)e=e.previousSibling;b=b.cloneRange();b.collapse(c);e?b.setStartAfter(e):b.setStartBefore(a);b=b.toString();return{node:e,offset:b.length}}};select.setCursorPos=
function(a,c,b){function e(f,g,j){function h(m){m.nodeType==3?k.push(m):forEach(m.childNodes,h)}if(g==0&&f&&!f.nextSibling){d["set"+j+"After"](f);return true}if(f=f?f.nextSibling:a.firstChild){if(g==0){d["set"+j+"Before"](f);return true}for(var k=[];;){for(;f&&!k.length;){h(f);f=f.nextSibling}var l=k.shift();if(!l)return false;var n=l.nodeValue.length;if(n>=g){d["set"+j](l,g);return true}g-=n}}}var d=document.createRange();b=b||c;e(b.node,b.offset,"End")&&e(c.node,c.offset,"Start")&&r(d)}}})();