/*
 http://www.gnu.org/licenses/gpl-3.0.html GNU General Public License v3

*/
$j(document).ready(function(){$j(".page_handle").hover(function(){$j(this).css("cursor","move")},function(){$j(this).css("cursor","auto")});$j(".file_name a").length>=1&&$j(".file_name a:[title]").tooltip({tipClass:"fileman-tip",layout:"<div>",effect:"fade",position:"center right",onShow:function(){var a=this.getTrigger().attr("href").match(/\.(jpe?g|png|gif|bmp)/gi)?this.getTrigger().attr("href"):"No preview available";this.getTrigger().attr("href").match(/\.(jpe?g|png|gif|bmp)/gi)?this.getTip().empty().append('<img src="'+
a+'"></img>'):this.getTip().empty().append(a)}});$j("#pages").Sortable({accept:"page",activeclass:"sortableactive",hoverclass:"sortablehover",helperclass:"sorthelper",opacity:0.5,handle:".page_handle",fit:true,axis:"vertically",revert:true,onChange:function(){serial=$j.SortSerialize("pages");$j.ajax({type:"POST",url:"admin/modules/ajax_pages.php",data:serial.hash,success:function(){}})}});$j(".more_upload").show();$j(".image_preview select").bind("change",preview)});
function preview(){$j(".lightbox").remove();var a=$j(this).find("option[@selected]").text();$j(this).parent().find(".lightbox").html();if(a!="-"){$j(this).parent().find(".more_upload").prepend('<a href="../files/images/'+a+'" onclick="" class="lightbox">preview</a> ');tb_init("a.lightbox")}else $j(this).parent().find(".lightbox").hide()}
function carouselInit(){$j(function(){$j("#carousel").jCarouselLite({start:pfxScroll-1,visible:3,scroll:2,btnNext:".next",btnPrev:".prev",circular:true,easing:"easeInOutQuad",speed:250,mouseWheel:true});$j("ul#mycarousel li").not("ul#mycarousel li.current").hover(function(){$j(this).children("a.link-dynamic").css("color","#204A87");$j(this).children("a.link-module").css("color","#4E9A06");$j(this).children("a.link-static").css("color","#8F5902");$j(this).children("a.link-plugin").css("color","#5C3566")},
function(){$j(this).children("a.c-link").css("color","#2E3436")})});$j(document).ready(function(){$j(".innav a.c-link:[title]").tooltip({tipClass:"carousel-tip",layout:"<div><div/>",effect:"fade",position:"top center"})})}function applyTablesort(){$j(function(){$j(document).ready(function(){$j(".tbl").tablesorter("debug",false);$j(".tbl_heading").hover(function(){$j(this).css("cursor","pointer")},function(){$j(this).css("cursor","auto")})})})}
function fetchJs(a){$j.ajaxSetup("async",false);$j.getScript("jscript/"+a+".js",function(){$j.ajaxSetup("async",true);a==="tablesorter"&&$j(".tbl").length>=1&&$j(document).ready(function(){applyTablesort()})})}function pfxMessage(){$j(document).ready(function(){if($j(".sys-message span").length>=1){$j(".sys-message").clone().appendTo("#message");$j("#message .sys-message").show();$j("div#message-wrap").slideDown("normal","easeInOutQuad")}})}
function pxfinderInit(){$j(".pxfinder").each(function(){$j(this).click(function(a){a.preventDefault();a=$j(this).attr("alt");window.opener.CKEDITOR.tools.callFunction(funcNum,pfxSiteUrl+"files"+a);window.close()})})}function autoName(){$j(".auto-name div div input#uname").one("focus",function(){if($j("input#uname").val()===""){var a=null;a=$j("input#realname").val();a=a.toLowerCase();a=a.split(" ")[parseInt(1)-1];$j(this).val(a)}})}
$j(function(){pfxMessage();$j("#carousel").length>=1&&carouselInit();scriptName="tablesorter";fetchJs(scriptName);scriptName="lightbox";fetchJs(scriptName);$j(".pxfinder").length>=1&&pxfinderInit();$j(".auto-name").length>=1&&autoName()});