CKEDITOR.dialog.add("pfxLink",function(p){function y(a){return a.replace(/'/g,"\\$&")}function A(a){var f,b=q.params,d,c;f=[q.name,"("];for(var e=0;e<b.length;e++){d=b[e].toLowerCase();c=a[d];e>0&&f.push(",");f.push("'",c?y(encodeURIComponent(a[d])):"","'")}f.push(")");return f.join("")}function B(a){for(var f,b=a.length,d=[],c=0;c<b;c++){f=a.charCodeAt(c);d.push(f)}return"String.fromCharCode("+d.join(",")+")"}var C=CKEDITOR.plugins.link,z=function(){var a=this.getDialog(),f=a.getContentElement("target",
"popupFeatures");a=a.getContentElement("target","linkTargetName");var b=this.getValue();if(f&&a){f=f.getElement();f.hide();a.setValue("");switch(b){case "frame":a.setLabel(p.lang.link.targetFrameName);a.getElement().show();break;case "popup":f.show();a.setLabel(p.lang.link.targetPopupName);a.getElement().show();break;default:a.setValue(b);a.getElement().hide()}}},D=/^javascript:/,E=/^mailto:([^?]+)(?:\?(.+))?$/,F=/subject=([^;?:@&=$,\/]*)/,G=/body=([^;?:@&=$,\/]*)/,H=/^#(.*)$/,I=/^((?:http|https|ftp|news):\/\/)?(.*)$/,
J=/^(_(?:self|top|parent|blank))$/,K=/^javascript:void\(location\.href='mailto:'\+String\.fromCharCode\(([^)]+)\)(?:\+'(.*)')?\)$/,L=/^javascript:([^(]+)\(([^)]+)\)$/,M=/\s*window.open\(\s*this\.href\s*,\s*(?:'([^']*)'|null)\s*,\s*'([^']*)'\s*\)\s*;\s*return\s*false;*\s*/,N=/(?:^|,)([^=]+)=(\d+|yes|no)/gi,O=function(a,f){var b=f&&(f.getAttribute("_cke_saved_href")||f.getAttribute("href"))||"",d,c,e={};if(b.match(D))if(r=="encode")b=b.replace(K,function(k,l,j){return"mailto:"+String.fromCharCode.apply(String,
l.split(","))+(j&&j.replace(/\\'/g,"'"))});else r&&b.replace(L,function(k,l,j){if(l==q.name){e.type="email";k=e.email={};l=/(^')|('$)/g;j=j.match(/[^,\s]+/g);for(var v=j.length,s,w,x=0;x<v;x++){s=decodeURIComponent;w=j[x].replace(l,"").replace(/\\'/g,"'");w=s(w);s=q.params[x].toLowerCase();k[s]=w}k.address=[k.name,k.domain].join("@")}});if(!e.type)if(d=b.match(H)){e.type="anchor";e.anchor={};e.anchor.name=e.anchor.id=d[1]}else if(d=b.match(E)){c=b.match(F);b=b.match(G);e.type="email";var h=e.email=
{};h.address=d[1];c&&(h.subject=decodeURIComponent(c[1]));b&&(h.body=decodeURIComponent(b[1]))}else if(b&&(c=b.match(I))){e.type="url";e.url={};e.url.protocol=c[1];e.url.url=c[2]}else e.type="url";if(f){d=f.getAttribute("target");e.target={};e.adv={};if(d)if(d.match(J))e.target.type=e.target.name=d;else{e.target.type="frame";e.target.name=d}else if(d=(d=f.getAttribute("_cke_pa_onclick")||f.getAttribute("onclick"))&&d.match(M)){e.target.type="popup";for(e.target.name=d[1];b=N.exec(d[2]);)if(b[2]==
"yes"||b[2]=="1")e.target[b[1]]=true;else if(isFinite(b[2]))e.target[b[1]]=b[2]}d=function(k,l){var j=f.getAttribute(l);if(j!==null)e.adv[k]=j||""};d("advId","id");d("advLangDir","dir");d("advAccessKey","accessKey");d("advName","name");d("advLangCode","lang");d("advTabIndex","tabindex");d("advTitle","title");d("advContentType","type");d("advCSSClasses","class");d("advCharset","charset");d("advStyles","style")}d=a.document.getElementsByTag("img");b=new CKEDITOR.dom.nodeList(a.document.$.anchors);c=
e.anchors=[];for(h=0;h<d.count();h++){var i=d.getItem(h);i.getAttribute("_cke_realelement")&&i.getAttribute("_cke_real_element_type")=="anchor"&&c.push(a.restoreRealElement(i))}for(h=0;h<b.count();h++)c.push(b.getItem(h));for(h=0;h<c.length;h++){i=c[h];c[h]={name:i.getAttribute("name"),id:i.getAttribute("id")}}this._.selectedElement=f;return e},m=function(a){if(a.target)this.setValue(a.target[this.id]||"")},t=function(a){if(a.adv)this.setValue(a.adv[this.id]||"")},n=function(a){a.target||(a.target=
{});a.target[this.id]=this.getValue()||""},u=function(a){a.adv||(a.adv={});a.adv[this.id]=this.getValue()||""},r=p.config.emailProtection||"";if(r&&r!="encode"){var q={};r.replace(/^([^(]+)\(([^)]+)\)$/,function(a,f,b){q.name=f;q.params=[];b.replace(/[^,\s]+/g,function(d){q.params.push(d)})})}var o=p.lang.common,g=p.lang.link;return{title:g.title,minWidth:350,minHeight:230,contents:[{id:"info",label:g.info,title:g.info,elements:[{id:"linkType",type:"select",label:g.type,"default":"url",items:[[g.toUrl,
"url"],[g.toAnchor,"anchor"],[g.toEmail,"email"]],onChange:function(){var a=this.getDialog(),f=["urlOptions","anchorOptions","emailOptions"],b=this.getValue(),d=a.definition.getContents("upload");d=d&&d.hidden;if(b=="url"){p.config.linkShowTargetTab&&a.showPage("target");d||a.showPage("upload")}else{a.hidePage("target");d||a.hidePage("upload")}for(d=0;d<f.length;d++){var c=a.getContentElement("info",f[d]);if(c){c=c.getElement().getParent().getParent();f[d]==b+"Options"?c.show():c.hide()}}},setup:function(a){a.type&&
this.setValue(a.type)},commit:function(a){a.type=this.getValue()}},{type:"vbox",id:"urlOptions",children:[{type:"hbox",widths:["25%","75%"],children:[{id:"protocol",type:"select",label:o.protocol,"default":"http://",items:[["http://\u200e","http://"],["https://\u200e","https://"],["ftp://\u200e","ftp://"],["news://\u200e","news://"],[g.other,""]],setup:function(a){if(a.url)this.setValue(a.url.protocol||"")},commit:function(a){if(!a.url)a.url={};a.url.protocol=this.getValue()}},{type:"text",id:"url",
label:o.url,required:true,onLoad:function(){this.allowOnChange=true},onKeyUp:function(){this.allowOnChange=false;var a=this.getDialog().getContentElement("info","protocol"),f=this.getValue(),b=/^((javascript:)|[#\/\.\?])/gi,d=/^(http|https|ftp|news):\/\/(?=.)/gi.exec(f);if(d){this.setValue(f.substr(d[0].length));a.setValue(d[0].toLowerCase())}else b.test(f)&&a.setValue("");this.allowOnChange=true},onChange:function(){this.allowOnChange&&this.onKeyUp()},validate:function(){var a=this.getDialog();if(a.getContentElement("info",
"linkType")&&a.getValueOf("info","linkType")!="url")return true;if(this.getDialog().fakeObj)return true;return CKEDITOR.dialog.validate.notEmpty(g.noUrl).apply(this)},setup:function(a){this.allowOnChange=false;a.url&&this.setValue(a.url.url);this.allowOnChange=true},commit:function(a){this.onChange();if(!a.url)a.url={};a.url.url=this.getValue();this.allowOnChange=false}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().show()}},{type:"button",id:"browse",
hidden:"true",filebrowser:"info:url",label:o.browseServer}]},{type:"vbox",id:"anchorOptions",width:260,align:"center",padding:0,children:[{type:"fieldset",id:"selectAnchorText",label:g.selectAnchor,setup:function(a){a.anchors.length>0?this.getElement().show():this.getElement().hide()},children:[{type:"hbox",id:"selectAnchor",children:[{type:"select",id:"anchorName","default":"",label:g.anchorName,style:"width: 100%;",items:[[""]],setup:function(a){this.clear();this.add("");for(var f=0;f<a.anchors.length;f++)a.anchors[f].name&&
this.add(a.anchors[f].name);a.anchor&&this.setValue(a.anchor.name);(a=this.getDialog().getContentElement("info","linkType"))&&a.getValue()=="email"&&this.focus()},commit:function(a){if(!a.anchor)a.anchor={};a.anchor.name=this.getValue()}},{type:"select",id:"anchorId","default":"",label:g.anchorId,style:"width: 100%;",items:[[""]],setup:function(a){this.clear();this.add("");for(var f=0;f<a.anchors.length;f++)a.anchors[f].id&&this.add(a.anchors[f].id);a.anchor&&this.setValue(a.anchor.id)},commit:function(a){if(!a.anchor)a.anchor=
{};a.anchor.id=this.getValue()}}],setup:function(a){a.anchors.length>0?this.getElement().show():this.getElement().hide()}}]},{type:"html",id:"noAnchors",style:"text-align: center;",html:'<div role="label" tabIndex="-1">'+CKEDITOR.tools.htmlEncode(g.noAnchors)+"</div>",focus:true,setup:function(a){a.anchors.length<1?this.getElement().show():this.getElement().hide()}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().hide()}},{type:"vbox",id:"emailOptions",padding:1,
children:[{type:"text",id:"emailAddress",label:g.emailAddress,required:true,validate:function(){var a=this.getDialog();if(!a.getContentElement("info","linkType")||a.getValueOf("info","linkType")!="email")return true;return CKEDITOR.dialog.validate.notEmpty(g.noEmail).apply(this)},setup:function(a){a.email&&this.setValue(a.email.address);(a=this.getDialog().getContentElement("info","linkType"))&&a.getValue()=="email"&&this.select()},commit:function(a){if(!a.email)a.email={};a.email.address=this.getValue()}},
{type:"text",id:"emailSubject",label:g.emailSubject,setup:function(a){a.email&&this.setValue(a.email.subject)},commit:function(a){if(!a.email)a.email={};a.email.subject=this.getValue()}},{type:"textarea",id:"emailBody",label:g.emailBody,rows:3,"default":"",setup:function(a){a.email&&this.setValue(a.email.body)},commit:function(a){if(!a.email)a.email={};a.email.body=this.getValue()}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().hide()}}]},{id:"target",
label:g.target,title:g.target,elements:[{type:"hbox",widths:["50%","50%"],children:[{type:"select",id:"linkTargetType",label:o.target,"default":"notSet",style:"width : 100%;",items:[[o.notSet,"notSet"],[g.targetFrame,"frame"],[g.targetPopup,"popup"],[o.targetNew,"_blank"],[o.targetTop,"_top"],[o.targetSelf,"_self"],[o.targetParent,"_parent"]],onChange:z,setup:function(a){a.target&&this.setValue(a.target.type);z.call(this)},commit:function(a){if(!a.target)a.target={};a.target.type=this.getValue()}},
{type:"text",id:"linkTargetName",label:g.targetFrameName,"default":"",setup:function(a){a.target&&this.setValue(a.target.name)},commit:function(a){if(!a.target)a.target={};a.target.name=this.getValue().replace(/\W/gi,"")}}]},{type:"vbox",width:260,align:"center",padding:2,id:"popupFeatures",children:[{type:"fieldset",label:g.popupFeatures,children:[{type:"hbox",children:[{type:"checkbox",id:"resizable",label:g.popupResizable,setup:m,commit:n},{type:"checkbox",id:"status",label:g.popupStatusBar,setup:m,
commit:n}]},{type:"hbox",children:[{type:"checkbox",id:"location",label:g.popupLocationBar,setup:m,commit:n},{type:"checkbox",id:"toolbar",label:g.popupToolbar,setup:m,commit:n}]},{type:"hbox",children:[{type:"checkbox",id:"menubar",label:g.popupMenuBar,setup:m,commit:n},{type:"checkbox",id:"fullscreen",label:g.popupFullScreen,setup:m,commit:n}]},{type:"hbox",children:[{type:"checkbox",id:"scrollbars",label:g.popupScrollBars,setup:m,commit:n},{type:"checkbox",id:"dependent",label:g.popupDependent,
setup:m,commit:n}]},{type:"hbox",children:[{type:"text",widths:["30%","70%"],labelLayout:"horizontal",label:g.popupWidth,id:"width",setup:m,commit:n},{type:"text",labelLayout:"horizontal",widths:["55%","45%"],label:g.popupLeft,id:"left",setup:m,commit:n}]},{type:"hbox",children:[{type:"text",labelLayout:"horizontal",widths:["30%","70%"],label:g.popupHeight,id:"height",setup:m,commit:n},{type:"text",labelLayout:"horizontal",label:g.popupTop,widths:["55%","45%"],id:"top",setup:m,commit:n}]}]}]}]},{id:"upload",
label:g.upload,title:g.upload,hidden:true,filebrowser:"uploadButton",elements:[{type:"file",id:"upload",label:o.upload,style:"height:40px",size:29},{type:"fileButton",id:"uploadButton",label:o.uploadSubmit,filebrowser:"info:url","for":["upload","upload"]}]},{id:"advanced",label:g.advanced,title:g.advanced,elements:[{type:"vbox",padding:1,children:[{type:"hbox",widths:["45%","35%","20%"],children:[{type:"text",id:"advId",label:g.id,setup:t,commit:u}]},{type:"hbox",widths:["45%","35%","20%"],children:[{type:"text",
label:g.name,id:"advName",setup:t,commit:u}]}]},{type:"vbox",padding:1,children:[{type:"hbox",widths:["45%","55%"],children:[{type:"text",label:g.advisoryTitle,"default":"",id:"advTitle",setup:t,commit:u}]},{type:"hbox",widths:["45%","55%"],children:[{type:"text",label:g.cssClasses,"default":"",id:"advCSSClasses",setup:t,commit:u}]},{type:"hbox",children:[{type:"text",label:g.styles,"default":"",id:"advStyles",setup:t,commit:u}]}]}]}],onShow:function(){this.fakeObj=false;var a=this.getParentEditor(),
f=a.getSelection(),b=null;if((b=C.getSelectedLink(a))&&b.hasAttribute("href"))f.selectElement(b);else if((b=f.getSelectedElement())&&b.is("img")&&b.getAttribute("_cke_real_element_type")&&b.getAttribute("_cke_real_element_type")=="anchor"){this.fakeObj=b;b=a.restoreRealElement(this.fakeObj);f.selectElement(this.fakeObj)}else b=null;this.setupContent(O.apply(this,[a,b]))},onOk:function(){var a={href:"javascript:void(0)/*"+CKEDITOR.tools.getNextNumber()+"*/"},f=[],b={href:a.href},d=this.getParentEditor();
this.commitContent(b);switch(b.type||"url"){case "url":var c=b.url&&b.url.protocol!=undefined?b.url.protocol:"http://",e=b.url&&b.url.url||"";a._cke_saved_href=e.indexOf("/")===0?e:c+e;break;case "anchor":c=b.anchor&&b.anchor.id;a._cke_saved_href="#"+(b.anchor&&b.anchor.name||c||"");break;case "email":var h=b.email;c=h.address;switch(r){case "":case "encode":e=encodeURIComponent(h.subject||"");var i=encodeURIComponent(h.body||"");h=[];e&&h.push("subject="+e);i&&h.push("body="+i);h=h.length?"?"+h.join("&"):
"";if(r=="encode"){c=["javascript:void(location.href='mailto:'+",B(c)];h&&c.push("+'",y(h),"'");c.push(")")}else c=["mailto:",c,h];break;default:c=c.split("@",2);h.name=c[0];h.domain=c[1];c=["javascript:",A(h)]}a._cke_saved_href=c.join("")}if(b.target)if(b.target.type=="popup"){e=["window.open(this.href, '",b.target.name||"","', '"];var k=["resizable","status","location","toolbar","menubar","fullscreen","scrollbars","dependent"];h=k.length;i=function(j){b.target[j]&&k.push(j+"="+b.target[j])};for(c=
0;c<h;c++)k[c]+=b.target[k[c]]?"=yes":"=no";i("width");i("left");i("height");i("top");e.push(k.join(","),"'); return false;");a._cke_pa_onclick=e.join("");f.push("target")}else{if(b.target.type!="notSet"&&b.target.name)a.target=b.target.name;else f.push("target");f.push("_cke_pa_onclick","onclick")}if(b.adv){c=function(j,v){var s=b.adv[j];if(s)a[v]=s;else f.push(v)};this._.selectedElement&&c("advId","id");c("advLangDir","dir");c("advAccessKey","accessKey");c("advName","name");c("advLangCode","lang");
c("advTabIndex","tabindex");c("advTitle","title");c("advContentType","type");c("advCSSClasses","class");c("advCharset","charset");c("advStyles","style")}if(this._.selectedElement){e=this._.selectedElement;h=e.getAttribute("_cke_saved_href");i=e.getHtml();if(CKEDITOR.env.ie&&a.name!=e.getAttribute("name")){var l=new CKEDITOR.dom.element('<a name="'+CKEDITOR.tools.htmlEncode(a.name)+'">',d.document);c=d.getSelection();e.moveChildren(l);e.copyAttributes(l,{name:1});l.replace(e);e=l;c.selectElement(e)}e.setAttributes(a);
e.removeAttributes(f);if(h==i||b.type=="email"&&i.indexOf("@")!=-1)e.setHtml(b.type=="email"?b.email.address:a._cke_saved_href);e.getAttribute("name")?e.addClass("cke_anchor"):e.removeClass("cke_anchor");this.fakeObj&&d.createFakeElement(e,"cke_anchor","anchor").replace(this.fakeObj);delete this._.selectedElement}else{c=d.getSelection();e=c.getRanges(true);if(e.length==1&&e[0].collapsed){h=new CKEDITOR.dom.text(b.type=="email"?b.email.address:a._cke_saved_href,d.document);e[0].insertNode(h);e[0].selectNodeContents(h);
c.selectRanges(e)}c=new CKEDITOR.style({element:"a",attributes:a});c.type=CKEDITOR.STYLE_INLINE;c.apply(d.document);if(b.adv&&b.adv.advId){d=this.getParentEditor().document.$.getElementsByTagName("a");for(c=0;c<d.length;c++)if(d[c].href==a.href){d[c].id=b.adv.advId;break}}}},onLoad:function(){p.config.linkShowAdvancedTab||this.hidePage("advanced");p.config.linkShowTargetTab||this.hidePage("target")},onFocus:function(){var a=this.getContentElement("info","linkType");if(a&&a.getValue()=="url"){a=this.getContentElement("info",
"url");a.select()}}}});