<?php
if (!defined('DIRECT_ACCESS')) {
	exit( header('Location: ../../') );
}
/**
 * PFX: Pixie Fork Xtreme.
 * Copyright (C) 2010, Tony White
 *
 * Largely based on code derived from :
 *
 * Pixie: The Small, Simple, Site Maker.
 * 
 * Licence: GNU General Public License v3
 * Copyright (C) 2010, Scott Evans
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/
 *
 * Title: Language File (English GB)
 *
 * @package PFX
 * @copyright 2008-2010 Scott Evans
 * @copyright 2010 Tony White
 * @author Scott Evans
 * @author Sam Collett
 * @author Tony White
 * @author Isa Worcs
 * @link http://heydojo.co.cc
 * @license http://www.gnu.org/licenses/gpl-3.0.html GNU General Public License v3
 *
 */
/* NOTE : No variables, arrays or constants are permitted to be added to this file. The only array permitted is $pfx_lang which must contain only strings of text */
$pfx_lang = array(
	/* System */
	'skip_to' => 'Skip to content',
	'view_site' => 'View site',
	'logout' => 'Logout',
	'license' => 'Released under the',
	'tag_line' => 'A Simple CMS.',
	'latest' => 'Latest',
	'latest_referrals' => 'Referrals',
	'latest_activity' => 'Activity',
	'feed_subscribe' => 'Subscribe',
	'rss_feed' => 'RSS Feed',
	'referral_link' => 'Referral Link',
	'page_miss' => 'Tried to access a page which is not public or does not exist',
	'when' => 'When?',
	'who' => 'Who?',
	'what' => 'What?',
	'from' => 'From?',
	'switch_to' => 'Switch to',
	'a_few_seconds' => 'A few seconds',
	'a_minute' => '1 minute',
	'minutes' => 'minutes',
	'a_hour' => '1 hour',
	'hours' => 'hours',
	'a_day' => '1 day',
	'days' => 'days',
	'ago' => 'ago.',
	'user' => 'User',
	'to' => 'to',
	'never' => 'Never',
	'daily' => 'Daily',
	'weekly' => 'Weekly',
	'monthly' => 'Monthly',
	'been' => 'there has been',
	'database_backup' => 'Database Backup',
	'database_info' => 'Make sure your database is backed up frequently. Use the button on the right to manually backup your database. The backups are stored in the files/sqlbackups/ folder and can be downloaded from the list below. Your most recent backup is highlighted.',
	'database_backups' => 'Backups',
	'download' => 'Download',
	'delete' => 'Delete',
	'delete_file' => 'Delete file?',
	'theme_info' => 'The currently installed themes are listed below. You can install more themes by uploading a theme into the admin/themes folder. More themes can be downloaded from <a href="http://heydojo.co.cc">heydojo.co.cc</a> or you can easily create your own using CSS. The current site theme is highlighted.',
	'theme_pick' => 'Pick a theme for your site',
	'theme_apply' => 'Apply this theme',
	'sure_delete_page' => 'Are you sure you want to delete the',
	'sure_empty_page' => 'Are you sure you want to empty the',
	'settings_page' => 'page',
	'settings_plugin' => 'plugin',
	'plugins' => 'Plugins',
	'plugin' => 'Plugin',
	'plugins_info' => 'Plugins bring extra functionality to certain pages of your website.',
	'empty' => 'Empty',
	'oops' => 'Ooops!',
	'feature_disabled' => 'This feature is currently disabled. in the next version of PFX hopefully, this will be sorted!',
	'pages_in_navigation' => 'Pages in navigation',
	'pages_in_navigation_info' => 'These pages appear in your websites navigation menu. To change the order of your pages, drag and drop them into position. The very first page at the top of the list will appear as the first item in your navigation menu.',
	'pages_outside_navigation' => 'Pages outside navigation',
	'pages_outside_navigation_info' => 'These pages are visible to the public but do not appear in your websites navigation.',
	'pages_disabled' => 'Disabled pages',
	'pages_disabled_info' => 'These pages are not viewable.',
	'edit_user' => 'Edit User',
	'create_user' => 'Create a new user',
	'create_user_info' => 'An email we be sent to the new user with details of how to login and a randomly generated password.',
	'user_info' => 'Below is a list of the users who have access to PFX. You can add more users to help manage your site by using the form on the right. The super user account is highlighted.',
	'user_delete_confirm' => 'Are you sure you want to delete user :',
	'tags' => 'Tags',
	'upload' => 'Upload',
	'file_manager_latest' => 'Latest Uploads',
	'file_manager_tagged' => 'All files tagged:',
	'filename' => 'Filename',
	'filedate' => 'Date Modified',
	'results_from' => 'Results from',
	'sure_delete_entry' => 'Delete entry',
	'from_the' => 'from the',
	'page_settings' => 'Page settings',
	'advanced' => 'Advanced',
	'your_site_has' => 'currently has',
	'visitors_online' => 'visitor(s) online.',
	'in_the_last' => 'In the last',
	'site_visitors' => 'Site Visitor(s)',
	'page_views' => 'Page Views',
	'spam_attacks' => 'Spam Attacks',
	'last_login_on' => 'Your last login was :',
	'quick' => 'Quick',
	'links' => 'Links',
	'new_entry' => 'Add a new ',
	'entry' => 'entry',
	'edit' => 'Edit ',
	'page' => 'page',
	'blog' => 'Blog',
	'search' => 'Search',
	'forums' => 'Forums',
	'downloads' => 'Downloads',
	'auto_backup' => 'Automatic Backup',
	'create_backup' => 'Create Backup',
	'button_backup' => 'Backup the database',
	'button_interval' => 'Set new interval',
	'page_type' => 'Page Type',
	'settings_page_new' => 'Create a new',
	'total_records' => 'Total records',
	'showing_from_record' => 'showing from record',
	'page(s)' => 'page(s)',
	'help' => 'Help',
	'static' => 'Static',
	'module' => 'Module',
	'statistics' => 'Statistics',
	'help_settings_page_type' => 'When adding a new page you can choose from three types:',
	'help_settings_page_dynamic' => 'Examples of dynamic pages are blogs and news pages. These pages support RSS feeds and commenting.',
	'help_settings_page_static' => 'A static page is simply a block of HTML (And PHP if you would like.) These pages are suited to static or rarely updated content.',
	'help_settings_page_module' => 'A module page adds specific content to your site. Modules can be downloaded from <a href="http://heydojo.co.cc">heydojo.co.cc</a>, an example of which is the events module. Modules are sometimes bundled with plugins.',
	'help_settings_page_plugin' => 'A plugin brings extra functionality to your website but do not show in the navigation menu.',
	'help_settings_user_type' => 'When adding a new user you can choose from three types :',
	'help_settings_user_admin' => '<b>Administrator</b> - Administrators have access to the whole of PFX, they can edit the settings, write content and do anything they like.',
	'help_settings_user_client' => '<b>Client</b> - A client can only add content to PFX, they are unable to edit the settings of a site.',
	'help_settings_user_user' => '<b>User</b> - A PFX user only has access to the Dashboard tab, they have a PFX profile and can see the website statistics.',
	'install_module' => 'Install a new module or plugin',
	'select_module' => 'Select the module or plugin you wish to activate',
	'all_installed' => 'All available modules and plugins are currently active and installed.',
	/* System messages */
	'bad_bot_block' => 'was banned from this website for bad bot behaviour.',
	'log_empty' => 'No log records to display. The log is empty.',
	'filemanager_empty' => 'No files found.',
	'error_save_settings' => 'Error saving settings.',
	'ok_save_settings' => 'Your new settings have been saved and applied.',
	'comment_spam' => 'Comment spam blocked.',
	'failed_login' => 'Failed login attempt.',
	'login_exceeded' => 'You have exceeded the maximum amount of attempts to login to PFX, please try again in 24 hours.',
	'logins_exceeded' => '3 failed login attempts detected. PFX has blocked this IP address for 24 hours.',
	'ok_login' => "logged in.",
	'ok_logout' => "logged out.",
	'failed_protected_page' => 'Unable to delete the 404 page, possible hack attempt.',
	'ok_delete_page' => 'Successfully deleted the',
	'ok_delete_entry_1' => 'Successfully deleted entry (#',
	'ok_delete_entry_2' => ') from the',
	'failed_delete_1' => 'Unable to delete item (#',
	'failed_delete_2' => '.)',
	'login_missing' => 'Please provide the required login information.',
	'login_incorrect' => 'Your login details are incorrect.',
	'forgotten_missing' => 'You did not provide a valid username or email address.',
	'forgotten_ok' => 'A new password has been sent to your email address.',
	'forgotten_log_error' => 'Failed attempt to reset password.',
	'forgotten_log_ok' => 'A new password was sent to ',
	'rss_access_attempt' => 'Unauthorised attempt to access a private RSS feed. You may need to re-subscribe to the feed from within PFX.',
	'unknown_error' => 'Something went wrong. It is possible (But not likely,) That the database is down.',
	'unknown_edit_url' => 'The URL supplied to edit this page is not valid.',
	'unknown_referrer' => 'Unknown Referrer',
	'profile_name_error' => 'Please enter your full name.',
	'profile_email_error' => 'Please provide a valid email address.',
	'profile_web_error' => 'Please provide a valid web address.',
	'profile_ok' => 'Your profile has been updated.',
	'profile_password_error' => 'PFX was unable to save your new password. Why not try again?',
	'profile_password_ok' => 'Your PFX password has been updated. You will need to use it next time you login.',
	'profile_password_invalid' => 'You did not supply a valid current password.',
	'profile_password_invalid_length' => 'Passwords must be at least 6 characters long.',
	'profile_password_match_error' => 'The passwords you supplied did not match.',
	'profile_password_missing' => 'Please provide all the required information.',
	'site_name_error' => 'Your site needs a name.',
	'site_url_error' => 'Please provide a valid website URL.',
	'private_key_error' => 'Please provide a reCaptcha private key.',
	'public_key_error' => 'Please provide a reCaptcha public key.',
	'backup_ok' => 'Successfully created a new backup of the database.',
	'backup_delete_ok' => 'Successfully deleted the backup :',
	'backup_delete_no' => 'You cannot delete the most recent backup.',
	'backup_delete_error' => 'PFX was unable to delete the backup.',
	'theme_ok' => 'The theme has been applied to your website.',
	'theme_error' => 'PFX was unable to change your theme.',
	'all_content_deleted' => 'All content was deleted from the',
	'user_delete_ok' => 'has been deleted from PFX.',
	'user_delete_error' => 'Unable to delete user',
	'user_name_missing' => 'Please provide a username.',
	'user_realname_missing' => 'Please provide a name.',
	'user_password_missing' => 'Please provide a password.',
	'user_email_error' => 'Please provide a valid email address.',
	'user_update_ok' => 'Saved new settings for',
	'user_duplicate' => 'A user with that username already exists, try another.',
	'user_new_ok' => 'Created new user:',
	'saved_new_settings_for' => 'Saved new settings for the',
	'file_upload_error' => 'PFX had a problem inserting the file information into database, the file may have been uploaded still.',
	'file_upload_tag_error' => 'Please make sure you tag your uploads.',
	'file_delete_ok' => 'Successfully deleted file :',
	'file_delete_fail' => 'PFX was unable to delete the file :',
	'form_build_fail' => 'Unable to build an editable form... did you supply the correct table details in your module?',
	'date_error' => 'You supplied an invalid date.',
	'email_error' => 'Please make sure you have entered a valid email address.',
	'url_error' => 'Please make sure you have entered a valid URL.',
	'is_required' => 'is a required field.',
	'saved_new' => 'Saved new entry',
	'in_the' => 'in the',
	'on_the' => 'on the',
	'saved_new_page' => 'Created new page',
	'save_update_entry' => 'Saved updates to entry',
	'bad_cookie' => 'Your session cookie has expired. You will need to login again.',
	'no_module_selected' => 'You did not select a module or plugin to install, try again.',
	'install_module_ok' => 'has been installed successfully.',
	'cron_ok' => 'PFX completed an automatic database backup.',
	'cron_not_ok' => 'Automatic database backup failed.',
	'interval_ok' => 'Automatic database backup interval changed.',
	'interval_not_ok' => 'Automatic database backup interval not changed.',
	'textarea_contains_php' => 'The editor has been disabled because the content contains php code.',
	'insuficient_privs' => 'You do not have sufficient user account priviledges to edit this content. Please contact the site\'s administrator and request that your user account be upgraded to administrator level if you really must edit this content.',
	/* Helper */
	'helper_plugin' => 'You are unable to edit the settings of plugins, you can however empty a plugin using the button above. Core plugins connot be deleted.',
	'helper_nocontent' => 'This page does not have any content, use the link above to add the first entry (The link is not available on the comments plugin.)',
	'helper_nopages' => 'A wise man once said that a website without pages is like a bird without wings... Its not going anywhere. Use the form on the right to add the first page to your site. Once you have done that this insightful message will disapear.',
	'helper_nopages404' => 'Your site only has one page, that page is the 404 error page and can be edited below.',
	'helper_nopagesadmin' => 'You can <a href="?s=settings">add more pages in the \'Settings\' section</a> of PFX.',
	'helper_nopagesuser' => 'Contact a site administrator and ask them to add some pages to your website.',
	'helper_search' => 'No entries were found. Try searching again.',
	/* Navigation */
	'nav1_settings' => 'Settings',
	'nav1_publish' => 'Publish',
	'nav1_home' => 'Dashboard',
	'nav2_home' => 'Home',
	'nav2_profile' => 'Profile',
	'nav2_security' => 'Password',
	'nav2_logs' => 'Logs',
	'nav2_delete' => 'Delete Account',
	'nav2_pages' => 'Pages',
	'nav2_files' => 'File Manager',
	'nav2_backup' => 'Backup',
	'nav2_users' => 'Users',
	'nav2_blocks' => 'Blocks',
	'nav2_theme' => 'Theme',
	'nav2_site' => 'Site',
	'nav2_settings' => 'Settings',
	/* Forms */
	'form_yes' => 'Yes',
	'form_no' => 'No',
	'form_login' => 'Login',
	'form_username' => 'Username',
	'form_password' => 'Password',
	'form_rememberme' => 'Remain logged in on this computer?',
	'form_forgotten' => 'Forgotten your password?',
	'form_returnto' => 'Return to ',
	'form_help_forgotten' => 'Please enter your email or username for your PFX account. Your password will be reset and emailed to you.',
	'form_resetpassword' => 'Reset Password',
	'form_name' => 'Full Name',
	'form_usernameoremail' => 'Username or Email address',
	'form_telephone' => 'Telephone',
	'form_email' => 'Email',
	'form_website' => 'My Website',
	'form_occupation' => 'Occupation',
	'form_address_street' => 'Street Address',
	'form_address_town' => 'Town',
	'form_address_county' => 'County',
	'form_address_pcode' => 'Post Code',
	'form_address_country' => 'Country',
	'form_address_biography' => 'Biography',
	'form_fl1' => 'My Favourite Links',
	'form_button_save' => 'Save',
	'form_button_update' => 'Update',
	'form_button_cancel' => 'Cancel',
	'form_button_back' => 'Go back',
	'form_button_install' => 'Install',
	'form_button_create_page' => 'Create page',
	'form_current_password' => 'Current Password',
	'form_new_password' => 'New Password',
	'form_confirm_password' => 'Confirm Password',
	'form_tags' => 'Tags',
	'form_content' => 'Content',
	'form_comments' => 'Comments',
	'form_public' => 'Public',
	'form_optional' => '(Optional.)',
	'form_required' => '*',
	'form_title' => 'Title',
	'form_posted' => 'Date &amp; Time',
	'form_date' => 'Date &amp; Time',
	'form_help_comments' => 'Would you like people to be able to comment on this post?',
	'form_help_public' => 'Would you like this post/page to be viewable by the public? (Select no to save it as a draft.)',
	'form_help_tags' => 'Tags work like categories and make things easier to find. Enter keywords separated by spaces.',
	'form_help_current_tags' => 'Suggestions:',
	'form_help_current_blocks' => 'Available Blocks :',
	'form_legend_site_settings' => 'Adjust the settings for your website',
	'form_site_name' => 'Site Name',
	'form_help_site_name' => 'What would you like your site to be called?',
	'form_page_name' => 'Slug/URL',
	'form_help_page_name' => 'This will be used to create the URL of your page (e.g. http://www.yoursite.com/<b>somepage</b>/)',
	'form_page_display_name' => 'Page Display Name',
	'form_help_page_display_name' => 'What would you like your page to be called?',
	'form_page_description' => 'Page Description',
	'form_help_page_description' => 'Write a description of your page.',
	'form_page_blocks' => 'Page Blocks',
	'form_help_page_blocks' => 'Blocks are the extra content that sit with your page. Block names should be separated with spaces. (Block handling may be improved upon in future versions of PFX.)',
	'form_searchable' => 'Searchable',
	'form_help_searchable' => 'Would you like this page to appear in public searches?',
	'form_posts_per_page' => 'Posts on this page',
	'form_help_posts_per_page' => 'How many entries would you like to show on this page?',
	'form_rss' => 'RSS',
	'form_help_rss' => 'Would you like this page to generate an RSS feed of its content?',
	'form_in_navigation' => 'In Navigation',
	'form_help_in_navigation' => 'Would you like this page to be shown in your websites navigation?',
	'form_is_contact' => 'Contact',
	'form_help_is_contact' => 'Should this user be contactable using the contact module?',
	'form_rte_user' => 'Rich text editor',
	'form_help_rte_user' => 'Should this user use the advanced rich text editor?',
	'form_site_url' => 'Site URL',
	'form_help_site_url' => 'What is the URL of your website? e.g. http://www.yoursite.com/somefolder/',
	'form_site_homepage' => 'Homepage',
	'form_help_homepage' => 'Which page of your site would you like visitors to see first?',
	'form_site_keywords' => 'Site Keywords',
	'form_help_site_keywords' => 'Write a list of no more than fourteen keywords separated by commas. (e.g. this,site,rules)',
	'form_site_author' => 'Site Author',
	'form_site_copyright' => 'Site Copyright',
	'form_site_curl' => 'Clean URLs?',
	'form_site_jquery' => 'jQuery?',
	'form_site_url_test_yes' => 'Your server appears to support clean urls.',
	'form_site_url_test_no' => 'Your server does not appear to support clean urls.',
	'form_site_gzip_test_yes' => 'Your server appears to support gzip compression.',
	'form_site_gzip_test_no' => 'Your server does not appear to support gzip compression.',
	'form_site_jquery_latest' => 'jQuery version?',
	'form_site_jquery_g' => 'Load jQuery from Google\'s servers?',
	'form_site_jquery_g_loc' => 'jQuery from Google api location?',
	'form_site_css_xhtml' => 'Is your site\'s xhtml and css valid?',
	'form_site_lightbox' => 'Use a lightbox in your theme?',
	'form_site_gzip' => 'Compress theme and admin area output using gzip compression?',
	'form_site_ie7_compat' => 'Internet explorer compatability?',
	'form_site_captcha' => 'Captcha?',
	'form_site_recaptcha_private_key' => 'ReCaptcha private key',
	'form_site_recaptcha_public_key' => 'ReCaptcha public key',
	'form_help_site_curl' => 'Would you like your site to use clean URLs? A clean URL looks like www.yoursite.com/clean/ as apposed to www.yoursite.com?s=clean. Clean URLs work on Linux hosts only.',
	'form_help_site_jquery' => 'Would you like the jQuery javascript library to be loaded by your site?',
	'form_help_site_jquery_latest' => 'Would you like to include a specific version of the jQuery javascript library from the location :',
	'form_help_site_jquery_g' => 'Would you like jQuery to be loaded from Google\'s api server to try to speed up your website?',
	'form_help_site_jquery_g_loc' => 'What url should your theme use to load jQuery from Google\'s api?',
	'form_help_site_css_xhtml' => 'Do you want to display a link in the footer of your theme to the w3c validators, to show that that your site follows web standards?',
	'form_help_site_lightbox' => 'Would you like to display images using <a href="http://code.google.com/p/sexy-lightbox/" title="Sexy LightBox" target="_blank">Sexy LightBox</a> to your site visitors?',
	'form_help_site_gzip' => 'Speed up your site using gzip compressed output?',
	'form_help_site_ie7_compat' => 'Would you like your theme to try to workaround Internet Explorer\'s inability to render vaild xhtml and css correctly, by using ie7 compatibility mode? (Recommended.)',
	'form_help_site_captcha' => 'Would you like site wide comment and contact forms to display a reCaptcha challenge to try to help reduce spam?',
	'form_help_site_recaptcha_private_key' => 'For extra security, you can specify your own reCaptcha keys. You can obtain key pairings from the <a href="http://recaptcha.net/" title="Get reCaptcha" target="_blank">reCaptcha</a> website.',
	'form_help_site_recaptcha_public_key' => 'The corresponding reCaptcha public key.',
	'form_legend_pfx_settings' => 'Adjust the way PFX behaves',
	'form_pfx_language' => 'Language',
	'form_help_pfx_language' => 'Select the language you wish to use.',
	'form_pfx_timezone' => 'Timezone',
	'form_help_pfx_timezone' => 'Select your current time zone so PFX can display the correct time.',
	'form_pfx_charset' => 'Character encoding set',
	'form_help_pfx_charset' => 'This setting effects the character encoding for PFX. Useful for various languages. UTF-8 is the recommended and tested default.',
	'form_pfx_date' => 'Date &amp; Time',
	'form_help_pfx_date' => 'Select your preferred date and time format.',
	'form_pfx_rte' => 'Rich Text Editor',
	'form_help_pfx_rte' => 'Would you like to use the Ckeditor text editor? (It makes editing your site really easy.)',
	'form_pfx_rte_img_class' => 'Rich Text Editor Image Class',
	'form_help_pfx_rte_img_class' => 'What class name would you like automatically added to images? (Leave blank for none.)',
	'form_pfx_rte_enter_mode' => 'Advanced Rich Text Editor Enter Key Mode &lt;br /&gt; Tag',
	'form_help_pfx_rte_enter_mode' => 'Yes to select an enter key press adds a &lt;br /&gt; tag, or No to wrap the text in &lt;p&gt;&lt;/p&gt; tags instead.',
	'form_pfx_logs' => 'Logs Expire',
	'form_pfx_log_bots' => 'Log web bots',
	'form_help_pfx_logs' => 'After how many days would you like to clear your log files?',
	'form_pfx_interval' => 'Interval',
	'form_help_pfx_interval' => 'How often would you like an automatic database backup created?',
	'form_pfx_sysmess' => 'System Message',
	'form_help_pfx_sysmess' => 'This message will be shown to each PFX user when they log into PFX.',
	'form_help_settings_page_type' => 'What type of page would you like to make?',
	'form_legend_user_settings' => 'User Settings',
	'form_user_username' => 'Username',
	'form_help_user_username' => 'Usernames cannot contain spaces.',
	'form_user_realname' => 'Full Name',
	'form_help_user_realname' => 'Enter the users full name.',
	'form_user_permissions' => 'Permissions',
	'form_help_user_permissions' => 'What permissions would you like this user to have?',
	'form_help_user_permissions_block' => 'What type of user will this be?',
	'form_button_create_user' => 'Create user',
	'form_upload_file' => 'File',
	'form_help_upload_file' => 'Select a file from your computer to upload.',
	'form_help_upload_tags' => 'Keywords separated by spaces.',
	'form_upload_replace_files' => 'Replace files?',
	'form_help_upload_replace_files' => 'Are you trying to replace an existing file?',
	'form_help_pfx_log_bots' => 'Do you want to show web bot visitor information in referral log output?',
	'form_search_words' => 'Keywords',
	'form_privs' => 'Page Permissions',
	'form_help_privs' => 'Who would you like to be able to edit this page?',
	'form_log_icon' => '<br />',
	'form_log_time' => 'When?',
	'form_user_id' => 'Who?',
	'form_user_ip' => 'Who?',
	'form_log_message' => 'What?',
	'form_not_set' => 'Not set',
	'form_this' => 'this',
	/* Email */
	'email_newpassword_subject_1' => 'PFX (',
	'email_newpassword_subject_2' => ') - New password',
	'email_changepassword_subject_1' => 'PFX (',
	'email_changepassword_subject_2' => ') - Changed password',
	'email_newpassword_message' => 'Your password has been set to : ',
	'email_account_close_message_1' => 'Your PFX account has been closed @ ',
	'email_account_close_message_2' => '. Please contact the administrator of the site for more information.',
	'email_account_close_subject_1' => 'PFX (',
	'email_account_close_subject_2' => ') - Account closed',
	'email_account_edit_subject_1' => 'PFX (',
	'email_account_edit_subject_2' => ') - Important information regarding your account',
	'email_account_new_subject_1' => 'PFX (',
	'email_account_new_subject_2' => ') - New account',
	/* Front end */
	'continue_reading' => 'Continue reading',
	'permalink' => 'Permalink',
	'theme' => 'Theme',
	'navigation' => 'Navigation',
	'skip_to_content' => 'Skip to content &raquo;',
	'skip_to_nav' => 'Skip to navigation &raquo;',
	'by' => 'By',
	'on' => 'on',
	'view' => 'View',
	'profile' => 'profile',
	'all_posts_tagged' => 'all posts tagged',
	'permalink_to' => 'Permanent link to',
	'comments' => 'Comments',
	'comment' => 'Comment',
	'no_comments' => 'No comments yet...',
	'comment_closed' => 'Comments are now closed.',
	'comment_thanks' => 'Thank you for your comment.',
	'comment_leave' => 'Leave a comment',
	'comment_form_info' => 'Comment form is <a href="http://gravatar.com" title="Get a Gravatar">Gravatar</a> and <a href="http://www.cocomment.com" title="Track and share your comments">coComment</a> enabled.',
	'comment_name' => 'Name',
	'comment_email' => 'Email',
	'comment_web' => 'Website',
	'comment_button_leave' => 'Submit your comment',
	'comment_name_error' => 'Please provide your name.',
	'comment_email_error' => 'Please provide a valid email address.',
	'comment_web_error' => 'Please provide a valid web address.',
	'comment_throttle_error' => 'You are posting comments too quickly, slow down.',
	'comment_comment_error' => 'Please provide a comment.',
	'comment_save_log' => 'commented on : ',
	'tagged' => 'Tagged',
	'tag' => 'Tag',
	'popular' => 'Most popular',
	'archives' => 'Archives',
	'posts' => 'posts',
	'last_updated' => 'Last updated',
	'edit_post' => 'Edit this post',
	'edit_page' => 'Edit this page',
	'popular_posts' => 'Popular Posts',
	'next_post' => 'Next post',
	'next_page' => 'Next page',
	'previous_post' => 'Previous post',
	'previous_page' => 'Previous page',
	'dynamic' => 'Dynamic',
	'dynamic_page' => 'Page',
	'file_del_filemanager_fail' => 'File delete failed. Please manually delete the file.',
	'upload_filemanager_fail' => 'Upload failed. Please check that the folder is writeable and has the correct permissions set.',
	'filemanager_max_upload' => 'Your host server will accept uploads for the maximum file size of : ',
	'ck_select_file' => 'Select',
	'captcha_text' => 'Please type the words in the image above.',
	'clients' => 'Clients',
	'admins' => 'Administrators',
	'no-desc' => 'No description',
	'comments_manage' => 'Manage comments.',
	'js_warn' => 'is best viewed using JavaScript. It is highly recommended that you use a Javascript enabled browser.',
	'ie6_warn' => 'The version of Internet Explorer you are using to visit this website using is very old. Please upgrade Internet Explorer now, install a <a href="http://www.opera.com/browser/" title="Get Opera browser">web browser</a> or if you really must use Internet Explorer 6, please install the <a href="http://code.google.com/chrome/chromeframe/" title="Get Chrome Frame">Chrome Frame</a> addon from Google.',
	'admin_js_warn' => 'The PFX admin area',
	'admin_php_ver' => 'Good. PFX is using PHP version ',
	'magic_quotes_suck' => 'PHP has been configured to use magic_quotes_gpc. If possible please contact your server Administrator and request that magic_quotes_gpc be set to off.',
	/* Installer */
	'installer' => 'Installer.',
	'install_js_warn' => 'The PFX installer requires a Javascript enabled browser. You must use a Javascript enabled browser to install PFX.',
	'installer_db_connect_failed' => 'The connection to the database could not be made. Please check and correct the connection information.',
	'installer_db_create_failed' => 'Error creating the database.',
	'installer_db_add_tables_failed' => 'Core database schema could not be created. The database is probbably not empty.',
	'installer_php_version_warn1' => 'WARNING! Your current PHP version :',
	'installer_php_version_warn2' => 'is unsupported. Please consult your server Administrator about upgrading php for security and compatability reasons.',
	'installer_log_warn1' => 'PFX was installed... Please remember to delete the install directory on your server.',
	'installer_log_warn2' => 'Please manually set the file .htaccess to the permission 644',
	'installer_log_warn3' => 'Please manually set the file  admin/config.php to the permission 640',
	'installer_log_warn4' => 'Please delete the install directory.',
	'installer_log_warn5' => 'Please manually set the file robots.txt to the permission 644',
	'installer_log_welcome1' => 'Welcome to PFX',
	'installer_log_welcome2' => 'running on PHP',
	'installer_log_welcome3' => 'be sure to visit',
	'installer_log_welcome4' => 'to check for updates.',
	'installer_hello' => 'Hi',
	'installer_congrats' => 'Congratulations!',
	'installer_good' => 'PFX was successfully installed.',
	'installer_details' => 'Here are your login details :',
	'installer_visit' => 'You can visit',
	'installer_view' => 'to view your site or',
	'installer_to_login' => 'to login.',
	'installer_thanks' => 'Thank You for installing PFX.',
	'installer_enjoy' => 'We hope you enjoy using it!',
	'installer_progress_info' => 'Installing. Please wait...',
	'installer_step1' => 'Step 1',
	'installer_step2' => 'Step 2',
	'installer_step3' => 'Step 3',
	'installer_welcome1' => 'Welcome to the',
	'installer_welcome2' => 'installer, just a few steps to go until you have your own PFX powered website. Firstly we need some details about your site :',
	'installer_welcome3' => 'Now PFX needs your database details :',
	'installer_welcome4' => 'Nearly finished!<br />Last step is to create the "Super User" account for PFX :',
	'installer_title1' => 'Site information',
	'installer_title2' => 'Database information',
	'installer_title3' => 'Super User information',
	'installer_title4' => 'Finish',
	'installer_curl1' => 'Turn on clean urls?',
	'installer_curl2' => 'A clean URL looks like www.yoursite.com/clean/ as apposed to www.yoursite.com?s=clean.',
	'installer_host1' => 'Host',
	'installer_host2' => 'Usually OK as',
	'installer_db_user_name' => 'Database Username',
	'installer_db_pwd' => 'Database Password',
	'installer_db_name' => 'Database Name',
	'installer_db_create1' => 'Create the database',
	'installer_db_create2' => 'Do you want the installer to create a new database for you?',
	'installer_db_prefix1' => 'Database Table Prefix',
	'installer_db_prefix2' => 'Example : <b>data_</b>',
	'installer_next' => 'Next',
	'installer_finish' => 'Finish',
	'installer_real_name1' => 'Your Name',
	'installer_real_name2' => 'Your real name',
	'installer_usr_name' => 'A login username',
	'installer_usr_email' => 'Your email address',
	'installer_usr_pwd' => 'A strong password',
	'installer_complete1' => 'Your new <b>PFX</b> web site is now setup and ready to use.</p>
		<p>If you would like to add <b>modules</b> or <b>themes</b>, be sure to visit the <a href="http://heydojo.co.cc" title="PFX" target="_blank">PFX website</a> to browse the collection. Please do also remember to delete the install directory within PFX (As soon as possible.) To secure your site.</p>
		<p>What would you like to do now ?',
	'installer_complete2' => 'Login and',
	'installer_complete3' => 'start adding content',
	'installer_complete4' => 'to your site?',
	'installer_complete5' => 'Visit the frontpage',
	'installer_complete6' => 'View your new frontpage',
	'installer_complete7' => 'Thank you for installing PFX!',
	'installer_js_lang_hostname' => 'Please type a valid hostname.',
	'installer_js_lang_username' => 'Please type a valid database user name.',
	'installer_js_lang_pwd' => 'Please type the correct password.',
	'installer_js_lang_db_pwd' => 'Please type the correct database name.',
	'installer_js_lang_real_name' => 'Please type a real name.',
	'installer_js_lang_login_name' => 'Please type a user name',
	'installer_js_lang_email' => 'Please type a valid email address.',
	'installer_js_lang_login_pwd' => 'Please type a password.',
	'installer_license_agree' => 'Do you agree to the terms of the software license?'
);